export const StepsEnum = Object.freeze({
    STEP_START: "STEP_START",
    STEP_GAME_1: "STEP_GAME_1",
    STEP_GAME_2: "STEP_GAME_2",
    STEP_QUIZ_1: "STEP_QUIZ_1",
    STEP_BONUS: "STEP_BONUS",
    STEP_QUIZ_2: "STEP_QUIZ_2",
    STEP_DEPOSIT: "STEP_DEPOSIT",
    STEP_END: "STEP_END",
})